name: action_slider
description: A slider to confirm actions and provide feedback on the success of these after subsequent loading.
version: 0.7.0
repository: https://github.com/splashbyte/action_slider

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:

funding:
  - https://buymeacoffee.com/splashbyte
  - https://ko-fi.com/splashbyte

screenshots:
  - description: 'This image shows three examples of ActionSlider.'
    path: screenshots/preview.webp
